### ISSUE TITLE
Decide if sealed should be the default

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-mixin#35]
Currently it is, this issue is to confirm that we want it to be so.

**Comment by matthewp** [comment]
Please thumbs up this issue so we can proceed with the conclusion that sealed: true should be the default for extended DefineClasses.

**Comment by justinbmeyer** [comment]
If we are going to support proxies, then sealed by default doesn't make a ton of sense. I'm unsure.

**Comment by matthewp** [comment]
Let's decide on https://github.com/canjs/can-define-class/issues/42 first then.

**Comment by matthewp** [comment]
We decided to do the proxy, which means it is unsealed by default.

**Comment by matthewp** [comment]
This is done.
