### ISSUE TITLE
Provide a way to describe default propdefinitions

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-mixin#36]
# Open questions

- default for properties
- what about # for arrays
- ¿ somehow default to maybe by default?

# Proposed API

I propose that instead of doing it like this (from can-define):

```js
class MyThing extends DefineClass {
  static define = {
    "*": {
      type: String
    }
  }
}
```

We instead add a `defaults` option:

```js
class MyThing extends DefineClass {
  static defaults = {
    type: String
  }
}
```

**Comment by phillipskevin** [comment]
I like this, but I think people might confuse `static defaults` with the `default` on a PropDefinition so maybe we want to use a different property name.

**Comment by justinbmeyer** [comment]
I like defaults too, but what would it be for `DefineArray`?  Currently `#` is for index properties and `*` is for all properties.

**Comment by justinbmeyer** [comment]
How could one specify "maybe by default"?

**Comment by matthewp** [comment]
Decided to go with `propertyDefaults` and `items`.
