### ISSUE TITLE
Make sure lastSet is provided to setters

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-mixin#40]
Notes from a discussion:

```
       - set([newVal] [,lastSet, ¿resolve?]) {
                    this.prop //-> side effect
                    return returnValue 
                        //-> 0 arguments ->
                        //         undefined -> leaves current value 
                        //         otherwise -> sets the value  
                    ¿ why not value ... property needs to be bound to know something was set  ?
```

Not sure if we had a conclusion here. @justinbmeyer I think brought up a case where `value()` doesn't work but I don't know what that is.

**Comment by phillipskevin** [comment]
I argue that we should just support normal JavaScript setters that can only have 1 argument. People should use `value` for everything else. When we discussed this, Justin's argument against this was:

> property needs to be bound to know something was set

I still think if you need this kind of side-effect, you should manually call `listenTo` in the connectedCallback to bind the property that is using `value`.

I think for now, we should just have single-argument setters and see if we run into enough use-cases to make these other signatures worthwhile.

**Comment by justinbmeyer** [comment]
ConnectedCallback might not be an option for models. Especially if you are dealing with a list.

**Comment by phillipskevin** [comment]
good point

**Comment by matthewp** [comment]
We need to support the `lastSet` but not `resolve`.
