### ISSUE TITLE
Calling new DefineClass

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-mixin#43]
What should happen when `new DefineClass()` is called. It should set all props like can-define does.

```js
var defineClass = new DefineClass({ a: 'b' });
```

**Comment by matthewp** [comment]
Depends on https://github.com/canjs/can-define-class/issues/35

**Comment by phillipskevin** [comment]
in `can-define` this makes the instance unsealed.

**Comment by matthewp** [comment]
Because of proxies and unsealed being the default, you can pass undefined values into the constructor, as well as setting values on the instance, for both DefineClass and extended DefineClasses.

**Comment by matthewp** [comment]
This was added as a test in can-define-object.
