### ISSUE TITLE
Object and Array class packages and exports

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define-mixin#55]
Lets figure out:

- the package name, 
- the package's export, and 
- the canjs export

For

- The Object Class, and
- The Array Class

Related:

-  #46 - Remove single export
- #1 - DefineClass name 
- #25 List variant name

Please add your ideas and pros and cons below

**Comment by justinbmeyer** [comment]
## DefinedObject and DefinedArray

- Packages: `can-defined-object`, `can-defined-array` or `can-defined/object/object` or `can-defined/array/array`.
- Package Export: `export default DefinedObject`, `default export DefinedArray`
- CanJS Exports: `DefinedObject`, `DefinedArray`

Pros:

- There's not `Class` in the export name (#1)
- Object and Array is the closest thing to what these produce.
- Complies with the convention of named exports matching the package name

Cons:

- If modules are `can-defined/array/` and `can-defined/object`, it's possible someone could install `can-define` and not be able to import `can-defined/x`.

__A note about the packageName ~= exportName convention__

Conventions are very useful in programming.  However, they are useful when repeated most of the time.  If `DefinedObject` is going to be one of the most used constructs in CanJS, I think it's important that it does not violate the naming convention.  Users will have to "check" what the package is and what they should name the import.

We as authors would know that `DefinedObject` is the one exception, but users will not realize that given how common its use is.

**Comment by phillipskevin** [comment]
## DefineClass and DefineArrayClass

- Packages: `can-define-class`
- Package Exports: `{ DefineClass, DefineArrayClass, mixinDefine }`
- CanJS Exports: same

Pros:

- One package
- Clear that it is used to create a class that is defined


Cons:

- Array version name is dumb
- Need to make sure the [export works](https://github.com/canjs/can-define-class/issues/46#issue-444950191)

**Comment by matthewp** [comment]
We're leaning towards going with: `can-define-object`, can-define-array`, `can-define-mixin`.

**Comment by matthewp** [comment]
This is done.
