### ISSUE TITLE
Clean up legacy can-define code

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define-mixin#62]
There is a lot of code that is left over from `can-define` that should be cleaned up

- warnings like https://github.com/canjs/can-define-mixin/blob/05c8e4c12512829e45bf639cd63310291ced12ef/src/define.js#L115

- signatures like `Default: Foo` that are no longer supported
- types like `type: "string"`

**Comment by matthewp** [comment]
Fixed by #75

**Comment by phillipskevin** [comment]
There is still some `type` vs `Type` stuff [here](https://github.com/canjs/can-define-mixin/blob/a44181785a00bd5f5cbe783d1cf82aaedb98bd5e/src/define.js#L214-L238) and  [here](https://github.com/canjs/can-define-mixin/blob/a44181785a00bd5f5cbe783d1cf82aaedb98bd5e/src/define.js#L282-L287) and some warnings that mention `can-define` [here](https://github.com/canjs/can-define-mixin/blob/a44181785a00bd5f5cbe783d1cf82aaedb98bd5e/src/define.js#L350) and [here](https://github.com/canjs/can-define-mixin/blob/a44181785a00bd5f5cbe783d1cf82aaedb98bd5e/src/define.js#L593).
